# Generated by Django 3.0.6 on 2020-08-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=10)),
                ('categoryId', models.IntegerField(default=1)),
                ('userId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(default=1)),
                ('longitude', models.IntegerField(default=2)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.Album')),
            ],
        ),
        migrations.CreateModel(
            name='IImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('thumbnailUrl', models.CharField(max_length=300)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iimages', to='api.Album')),
            ],
        ),
    ]
